---
title: "Analaisis_Salarios"
author: "Kevin Rivas y John Astwood"
date: "2023-08-15"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(corrplot)
library(forcats)
```

## R Markdown

```{r cars}
# Set the working directory to the location of the CSV file
setwd("/Users/kevinrivas/Documents/R")

# Read the CSV file
data <- read.csv("data_salarios.csv")  # Replace "filename.csv" with the actual CSV file's name
data <- subset(data, age <= 70 & age>=18)


```

## Graficos

```{r pressure}
colSums(is.na(data))


ggplot(data, aes(y = fct_lump(factor(job_simp), n = 25))) +
  geom_bar(stat = "count") +
  theme_minimal()

ggplot(data, aes(y = fct_lump(factor(Salary.Estimate), n = 20))) +
  geom_bar(stat = "count") +
  theme_minimal()

ggplot(data, aes(x = age, y = avg_salary)) +
  geom_point(color = "steelblue") +
  ggtitle("Age vs. Average Salary") +
  xlab("Age") +
  ylab("Average Salary") +
  theme_minimal()

ggplot(data, aes(y = age)) +
  geom_boxplot(fill = "steelblue") +
  ggtitle("Box Plot of Age") +
  ylab("Age") +
  theme_minimal()


# Seleccionar solo las variables numéricas
numeric_vars <- select_if(data, is.numeric)

# Calcular la matriz de correlación para variables numéricas
correlation_matrix <- cor(numeric_vars)

# Mostrar la matriz de correlación utilizando corrplot
correlation_matrix
# Perform linear regression
reg_model <- lm(avg_salary ~ job_state +excel+python_yn+R_yn +job_simp,data= data)

# Print the summary of the regression model
summary(reg_model)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
